In [1]:
import numpy as np
import pandas as pd

In [2]:
house=pd.read_csv(r"House price prediction.csv")
house

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [3]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [4]:
house.dtypes

Id            int64
Area          int64
Bedrooms      int64
Bathrooms     int64
Floors        int64
YearBuilt     int64
Location     object
Condition    object
Garage       object
Price         int64
dtype: object

In [5]:
house.columns.tolist()

['Id',
 'Area',
 'Bedrooms',
 'Bathrooms',
 'Floors',
 'YearBuilt',
 'Location',
 'Condition',
 'Garage',
 'Price']

In [6]:
house.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [7]:
house.shape

(2000, 10)

In [8]:
house["Id"].unique()

array([   1,    2,    3, ..., 1998, 1999, 2000], shape=(2000,))

In [9]:
house["Condition"].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [10]:
house["Bedrooms"].unique()

array([5, 2, 4, 1, 3])

In [11]:
house["Garage"].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
house["Location"].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [13]:
#ordinal encoding
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Excellent","Good","Fair","Poor"]])
house["Condition"]=oe.fit_transform(house[["Condition"]])
house

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,0.0,No,149919
1,2,4272,5,4,3,1958,Downtown,0.0,No,424998
2,3,3592,2,2,3,1938,Downtown,1.0,No,266746
3,4,966,4,2,2,1902,Suburban,2.0,Yes,244020
4,5,4926,1,4,2,1975,Downtown,2.0,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,3.0,No,295620
1996,1997,3046,5,2,1,2019,Suburban,3.0,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,3.0,No,476925
1998,1999,4062,3,1,2,1936,Urban,0.0,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,2.0,No,482525

In [14]:
#one hot or nominal encoding
house=pd.get_dummies(house,columns=["Garage"],drop_first=True,dtype=int)
house

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Price,Garage_Yes
0,1,1360,5,4,3,1970,Downtown,0.0,149919,0
1,2,4272,5,4,3,1958,Downtown,0.0,424998,0
2,3,3592,2,2,3,1938,Downtown,1.0,266746,0
3,4,966,4,2,2,1902,Suburban,2.0,244020,1
4,5,4926,1,4,2,1975,Downtown,2.0,636056,1
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,3.0,295620,0
1996,1997,3046,5,2,1,2019,Suburban,3.0,580929,1
1997,1998,1062,5,1,2,1903,Rural,3.0,476925,0
1998,1999,4062,3,1,2,1936,Urban,0.0,161119,1
1999,2000,2989,5,1,3,1903,Suburban,2.0,482525,0

In [15]:
#ordinal encoding
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[["Downtown", "Suburban", "Urban", "Rural"]])
house["Location"]=oe.fit_transform(house[["Location"]])
house

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Price,Garage_Yes
0,1,1360,5,4,3,1970,0.0,0.0,149919,0
1,2,4272,5,4,3,1958,0.0,0.0,424998,0
2,3,3592,2,2,3,1938,0.0,1.0,266746,0
3,4,966,4,2,2,1902,1.0,2.0,244020,1
4,5,4926,1,4,2,1975,0.0,2.0,636056,1
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,1.0,3.0,295620,0
1996,1997,3046,5,2,1,2019,1.0,3.0,580929,1
1997,1998,1062,5,1,2,1903,3.0,3.0,476925,0
1998,1999,4062,3,1,2,1936,2.0,0.0,161119,1
1999,2000,2989,5,1,3,1903,1.0,2.0,482525,0

In [16]:
#Separate X and Y
X=house.drop(columns="Price")
Y=house["Price"]

In [17]:
print("X shape:",X.shape)
print("Y shape:",Y.shape)

X shape: (2000, 9)
Y shape: (2000,)

In [18]:
#Train-Test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [19]:
print("X-train:",X_train.shape)
print("X-test:",X_test.shape)
print("Y-train:",Y_train.shape)
print("Y-test:",Y_test.shape)

X-train: (1600, 9)
X-test: (400, 9)
Y-train: (1600,)
Y-test: (400,)

In [20]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [21]:
y_scaler = StandardScaler()

Y_train = y_scaler.fit_transform(Y_train.values.reshape(-1,1))
Y_test = y_scaler.transform(Y_test.values.reshape(-1,1))

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
#design of ANN model
house=Sequential()

house.add(Dense(input_dim=9,units=32,activation="relu"))
house.add(Dense(units=16,activation="relu"))
house.add(Dense(units=8,activation="relu"))
house.add(Dense(1))

C:\Users\LoQ\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
#compile the data
house.compile(optimizer="adam",loss="mean_squared_error",metrics=["mae"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [25]:
#fit the train data
house.fit(X_train,Y_train,batch_size=32,epochs=200,validation_split=0.2)

Epoch 1/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 1.0343 - mae: 0.8761 - val_loss: 0.9614 - val_mae: 0.8428
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0064 - mae: 0.8670 - val_loss: 0.9531 - val_mae: 0.8388
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9971 - mae: 0.8627 - val_loss: 0.9509 - val_mae: 0.8379
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9895 - mae: 0.8591 - val_loss: 0.9494 - val_mae: 0.8360
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9829 - mae: 0.8559 - val_loss: 0.9465 - val_mae: 0.8358
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9773 - mae: 0.8532 - val_loss: 0.9507 - val_mae: 0.8364
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9726 - mae: 0.8510 - val_loss: 0.9443 - val_mae: 0.8354
Epoch 8/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9680 - mae: 0.8480 - val_loss: 0.9467 - val_mae: 0.8364
Epoch 9/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9628 - mae: 0.8464 - val_loss: 0.9482 - val_mae: 0.8361
Epoch 10/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9586 - mae: 0.8427 - val_loss: 0.9488 - val_mae: 0.8380
Epoch 11/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9537 - mae: 0.8401 - val_loss: 0.9507 - val_mae: 0.8362
Epoch 12/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9459 - mae: 0.8370 - val_loss: 0.9507 - val_mae: 0.8374
Epoch 13/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9421 - mae: 0.8343 - val_loss: 0.9576 - val_mae: 0.8397
Epoch 14/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9364 - mae: 0.8312 - val_loss: 0.9585 - val_mae: 0.8398
Epoch 15/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9305 - mae: 0.8271 - val_loss: 0.9717 - val_mae: 0.8424
Epoch 16/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9250 - mae: 0.8247 - val_loss: 0.9714 - val_mae: 0.8423
Epoch 17/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9166 - mae: 0.8198 - val_loss: 0.9691 - val_mae: 0.8457
Epoch 18/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9139 - mae: 0.8187 - val_loss: 0.9822 - val_mae: 0.8461
Epoch 19/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9090 - mae: 0.8153 - val_loss: 0.9922 - val_mae: 0.8490
Epoch 20/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9008 - mae: 0.8104 - val_loss: 0.9873 - val_mae: 0.8497
Epoch 21/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8939 - mae: 0.8079 - val_loss: 0.9894 - val_mae: 0.8516
Epoch 22/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8845 - mae: 0.8021 - val_loss: 0.9996 - val_mae: 0.8524
Epoch 23/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8777 - mae: 0.7991 - val_loss: 0.9979 - val_mae: 0.8531
Epoch 24/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8731 - mae: 0.7978 - val_loss: 1.0101 - val_mae: 0.8559
Epoch 25/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8686 - mae: 0.7931 - val_loss: 1.0054 - val_mae: 0.8563
Epoch 26/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8611 - mae: 0.7911 - val_loss: 1.0128 - val_mae: 0.8556
Epoch 27/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8501 - mae: 0.7859 - val_loss: 1.0210 - val_mae: 0.8590
Epoch 28/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8451 - mae: 0.7818 - val_loss: 1.0307 - val_mae: 0.8634
Epoch 29/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8386 - mae: 0.7807 - val_loss: 1.0365 - val_mae: 0.8639
Epoch 30/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8361 - mae: 0.7788 - val_loss: 1.0292 - val_mae: 0.8660
Epoch 31/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8314 - mae: 0.7743 - val_loss: 1.0399 - val_mae: 0.8630
Epoch 32/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8187 - mae: 0.7674 - val_loss: 1.0502 - val_mae: 0.8680
Epoch 33/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8120 - mae: 0.7639 - val_loss: 1.0505 - val_mae: 0.8678
Epoch 34/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8072 - mae: 0.7615 - val_loss: 1.0505 - val_mae: 0.8730
Epoch 35/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8027 - mae: 0.7563 - val_loss: 1.0567 - val_mae: 0.8705
Epoch 36/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7923 - mae: 0.7524 - val_loss: 1.0724 - val_mae: 0.8704
Epoch 37/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7895 - mae: 0.7513 - val_loss: 1.0696 - val_mae: 0.8726
Epoch 38/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7835 - mae: 0.7477 - val_loss: 1.0738 - val_mae: 0.8751
Epoch 39/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7748 - mae: 0.7447 - val_loss: 1.0846 - val_mae: 0.8745
Epoch 40/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7739 - mae: 0.7398 - val_loss: 1.0844 - val_mae: 0.8780
Epoch 41/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7625 - mae: 0.7367 - val_loss: 1.0869 - val_mae: 0.8812
Epoch 42/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7578 - mae: 0.7328 - val_loss: 1.1162 - val_mae: 0.8806
Epoch 43/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7597 - mae: 0.7333 - val_loss: 1.1056 - val_mae: 0.8787
Epoch 44/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7515 - mae: 0.7299 - val_loss: 1.1221 - val_mae: 0.8872
Epoch 45/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7457 - mae: 0.7257 - val_loss: 1.1394 - val_mae: 0.8903
Epoch 46/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7393 - mae: 0.7226 - val_loss: 1.1114 - val_mae: 0.8848
Epoch 47/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7314 - mae: 0.7186 - val_loss: 1.1216 - val_mae: 0.8846
Epoch 48/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7238 - mae: 0.7149 - val_loss: 1.1206 - val_mae: 0.8886
Epoch 49/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7188 - mae: 0.7118 - val_loss: 1.1338 - val_mae: 0.8929
Epoch 50/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7165 - mae: 0.7097 - val_loss: 1.1276 - val_mae: 0.8812
Epoch 51/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7156 - mae: 0.7062 - val_loss: 1.1265 - val_mae: 0.8868
Epoch 52/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7034 - mae: 0.7026 - val_loss: 1.1510 - val_mae: 0.8891
Epoch 53/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7003 - mae: 0.6995 - val_loss: 1.1556 - val_mae: 0.8964
Epoch 54/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6983 - mae: 0.6968 - val_loss: 1.1484 - val_mae: 0.8918
Epoch 55/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6899 - mae: 0.6943 - val_loss: 1.1537 - val_mae: 0.8930
Epoch 56/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6841 - mae: 0.6890 - val_loss: 1.1628 - val_mae: 0.9019
Epoch 57/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6768 - mae: 0.6872 - val_loss: 1.1920 - val_mae: 0.9025
Epoch 58/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6766 - mae: 0.6847 - val_loss: 1.1717 - val_mae: 0.8993
Epoch 59/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6708 - mae: 0.6819 - val_loss: 1.1804 - val_mae: 0.9004
Epoch 60/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6653 - mae: 0.6792 - val_loss: 1.1975 - val_mae: 0.9012
Epoch 61/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6666 - mae: 0.6772 - val_loss: 1.1933 - val_mae: 0.9032
Epoch 62/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6548 - mae: 0.6715 - val_loss: 1.1888 - val_mae: 0.9114
Epoch 63/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6532 - mae: 0.6722 - val_loss: 1.1834 - val_mae: 0.9036
Epoch 64/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6567 - mae: 0.6717 - val_loss: 1.2041 - val_mae: 0.9131
Epoch 65/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6448 - mae: 0.6661 - val_loss: 1.2116 - val_mae: 0.9136
Epoch 66/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6356 - mae: 0.6594 - val_loss: 1.2078 - val_mae: 0.9173
Epoch 67/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6382 - mae: 0.6618 - val_loss: 1.2204 - val_mae: 0.9205
Epoch 68/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6337 - mae: 0.6591 - val_loss: 1.2446 - val_mae: 0.9174
Epoch 69/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6280 - mae: 0.6548 - val_loss: 1.2242 - val_mae: 0.9194
Epoch 70/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6264 - mae: 0.6536 - val_loss: 1.2053 - val_mae: 0.9117
Epoch 71/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6253 - mae: 0.6543 - val_loss: 1.2044 - val_mae: 0.9153
Epoch 72/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6153 - mae: 0.6479 - val_loss: 1.2162 - val_mae: 0.9186
Epoch 73/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6153 - mae: 0.6466 - val_loss: 1.2346 - val_mae: 0.9209
Epoch 74/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6061 - mae: 0.6432 - val_loss: 1.2322 - val_mae: 0.9208
Epoch 75/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6095 - mae: 0.6428 - val_loss: 1.2412 - val_mae: 0.9267
Epoch 76/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6023 - mae: 0.6403 - val_loss: 1.2552 - val_mae: 0.9258
Epoch 77/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5967 - mae: 0.6368 - val_loss: 1.2638 - val_mae: 0.9323
Epoch 78/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5985 - mae: 0.6371 - val_loss: 1.2615 - val_mae: 0.9271
Epoch 79/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5909 - mae: 0.6337 - val_loss: 1.2513 - val_mae: 0.9266
Epoch 80/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5854 - mae: 0.6293 - val_loss: 1.2688 - val_mae: 0.9318
Epoch 81/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5811 - mae: 0.6274 - val_loss: 1.2662 - val_mae: 0.9326
Epoch 82/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5785 - mae: 0.6257 - val_loss: 1.2793 - val_mae: 0.9354
Epoch 83/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5737 - mae: 0.6200 - val_loss: 1.3116 - val_mae: 0.9442
Epoch 84/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5689 - mae: 0.6179 - val_loss: 1.3117 - val_mae: 0.9445
Epoch 85/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5729 - mae: 0.6205 - val_loss: 1.2886 - val_mae: 0.9375
Epoch 86/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5676 - mae: 0.6178 - val_loss: 1.3038 - val_mae: 0.9450
Epoch 87/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5594 - mae: 0.6099 - val_loss: 1.3509 - val_mae: 0.9519
Epoch 88/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5597 - mae: 0.6143 - val_loss: 1.3214 - val_mae: 0.9488
Epoch 89/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5573 - mae: 0.6114 - val_loss: 1.3081 - val_mae: 0.9425
Epoch 90/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5570 - mae: 0.6079 - val_loss: 1.3268 - val_mae: 0.9509
Epoch 91/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5541 - mae: 0.6102 - val_loss: 1.3373 - val_mae: 0.9517
Epoch 92/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5498 - mae: 0.6046 - val_loss: 1.3386 - val_mae: 0.9501
Epoch 93/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5474 - mae: 0.6049 - val_loss: 1.3258 - val_mae: 0.9493
Epoch 94/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5460 - mae: 0.6008 - val_loss: 1.3428 - val_mae: 0.9549
Epoch 95/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5386 - mae: 0.5980 - val_loss: 1.3583 - val_mae: 0.9541
Epoch 96/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5398 - mae: 0.5991 - val_loss: 1.3708 - val_mae: 0.9605
Epoch 97/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5399 - mae: 0.6013 - val_loss: 1.3511 - val_mae: 0.9539
Epoch 98/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5344 - mae: 0.5955 - val_loss: 1.3661 - val_mae: 0.9600
Epoch 99/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5333 - mae: 0.5957 - val_loss: 1.3640 - val_mae: 0.9558
Epoch 100/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5333 - mae: 0.5942 - val_loss: 1.3566 - val_mae: 0.9599
Epoch 101/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5264 - mae: 0.5910 - val_loss: 1.3628 - val_mae: 0.9544
Epoch 102/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5276 - mae: 0.5894 - val_loss: 1.3557 - val_mae: 0.9558
Epoch 103/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5242 - mae: 0.5878 - val_loss: 1.3900 - val_mae: 0.9644
Epoch 104/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5273 - mae: 0.5868 - val_loss: 1.3949 - val_mae: 0.9661
Epoch 105/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5181 - mae: 0.5848 - val_loss: 1.3768 - val_mae: 0.9596
Epoch 106/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5126 - mae: 0.5792 - val_loss: 1.3927 - val_mae: 0.9716
Epoch 107/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5191 - mae: 0.5851 - val_loss: 1.3721 - val_mae: 0.9589
Epoch 108/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5192 - mae: 0.5835 - val_loss: 1.3799 - val_mae: 0.9628
Epoch 109/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5194 - mae: 0.5831 - val_loss: 1.3953 - val_mae: 0.9686
Epoch 110/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5150 - mae: 0.5832 - val_loss: 1.3817 - val_mae: 0.9649
Epoch 111/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5139 - mae: 0.5818 - val_loss: 1.3937 - val_mae: 0.9700
Epoch 112/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5102 - mae: 0.5776 - val_loss: 1.4123 - val_mae: 0.9686
Epoch 113/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5058 - mae: 0.5734 - val_loss: 1.4425 - val_mae: 0.9815
Epoch 114/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5030 - mae: 0.5742 - val_loss: 1.4127 - val_mae: 0.9726
Epoch 115/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5018 - mae: 0.5759 - val_loss: 1.4053 - val_mae: 0.9655
Epoch 116/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4992 - mae: 0.5731 - val_loss: 1.4336 - val_mae: 0.9835
Epoch 117/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4933 - mae: 0.5670 - val_loss: 1.4128 - val_mae: 0.9737
Epoch 118/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4880 - mae: 0.5610 - val_loss: 1.4203 - val_mae: 0.9772
Epoch 119/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4871 - mae: 0.5633 - val_loss: 1.3962 - val_mae: 0.9684
Epoch 120/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4872 - mae: 0.5642 - val_loss: 1.4394 - val_mae: 0.9827
Epoch 121/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4899 - mae: 0.5640 - val_loss: 1.4351 - val_mae: 0.9791
Epoch 122/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4833 - mae: 0.5619 - val_loss: 1.4448 - val_mae: 0.9826
Epoch 123/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4840 - mae: 0.5600 - val_loss: 1.4447 - val_mae: 0.9864
Epoch 124/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4804 - mae: 0.5578 - val_loss: 1.4331 - val_mae: 0.9780
Epoch 125/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4812 - mae: 0.5556 - val_loss: 1.4509 - val_mae: 0.9840
Epoch 126/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4794 - mae: 0.5562 - val_loss: 1.4471 - val_mae: 0.9790
Epoch 127/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4825 - mae: 0.5601 - val_loss: 1.4491 - val_mae: 0.9885
Epoch 128/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4775 - mae: 0.5567 - val_loss: 1.4592 - val_mae: 0.9862
Epoch 129/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4803 - mae: 0.5586 - val_loss: 1.4622 - val_mae: 0.9884
Epoch 130/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4735 - mae: 0.5544 - val_loss: 1.4549 - val_mae: 0.9832
Epoch 131/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4692 - mae: 0.5492 - val_loss: 1.4609 - val_mae: 0.9845
Epoch 132/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4783 - mae: 0.5549 - val_loss: 1.4830 - val_mae: 0.9928
Epoch 133/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4662 - mae: 0.5499 - val_loss: 1.4464 - val_mae: 0.9856
Epoch 134/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4786 - mae: 0.5567 - val_loss: 1.4884 - val_mae: 0.9962
Epoch 135/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4640 - mae: 0.5480 - val_loss: 1.4753 - val_mae: 0.9954
Epoch 136/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4733 - mae: 0.5528 - val_loss: 1.4435 - val_mae: 0.9856
Epoch 137/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4628 - mae: 0.5447 - val_loss: 1.4567 - val_mae: 0.9880
Epoch 138/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4729 - mae: 0.5494 - val_loss: 1.4571 - val_mae: 0.9873
Epoch 139/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4609 - mae: 0.5432 - val_loss: 1.4765 - val_mae: 0.9939
Epoch 140/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4606 - mae: 0.5452 - val_loss: 1.4781 - val_mae: 0.9937
Epoch 141/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4544 - mae: 0.5390 - val_loss: 1.4509 - val_mae: 0.9825
Epoch 142/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4522 - mae: 0.5374 - val_loss: 1.4853 - val_mae: 0.9944
Epoch 143/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4598 - mae: 0.5424 - val_loss: 1.4998 - val_mae: 0.9995
Epoch 144/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4578 - mae: 0.5410 - val_loss: 1.4714 - val_mae: 0.9899
Epoch 145/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4531 - mae: 0.5436 - val_loss: 1.4745 - val_mae: 0.9910
Epoch 146/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4564 - mae: 0.5421 - val_loss: 1.5008 - val_mae: 1.0003
Epoch 147/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4505 - mae: 0.5367 - val_loss: 1.4772 - val_mae: 0.9937
Epoch 148/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4470 - mae: 0.5347 - val_loss: 1.5075 - val_mae: 1.0017
Epoch 149/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4469 - mae: 0.5338 - val_loss: 1.5119 - val_mae: 1.0061
Epoch 150/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4518 - mae: 0.5393 - val_loss: 1.5020 - val_mae: 1.0033
Epoch 151/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4476 - mae: 0.5350 - val_loss: 1.4872 - val_mae: 0.9967
Epoch 152/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4422 - mae: 0.5312 - val_loss: 1.4877 - val_mae: 0.9974
Epoch 153/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4452 - mae: 0.5306 - val_loss: 1.5209 - val_mae: 1.0087
Epoch 154/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4403 - mae: 0.5306 - val_loss: 1.4891 - val_mae: 0.9965
Epoch 155/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4384 - mae: 0.5265 - val_loss: 1.5268 - val_mae: 1.0068
Epoch 156/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4445 - mae: 0.5328 - val_loss: 1.5043 - val_mae: 1.0033
Epoch 157/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4386 - mae: 0.5279 - val_loss: 1.4975 - val_mae: 1.0011
Epoch 158/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4347 - mae: 0.5236 - val_loss: 1.5143 - val_mae: 1.0053
Epoch 159/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4410 - mae: 0.5295 - val_loss: 1.5237 - val_mae: 1.0084
Epoch 160/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4335 - mae: 0.5264 - val_loss: 1.5423 - val_mae: 1.0177
Epoch 161/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4370 - mae: 0.5278 - val_loss: 1.5323 - val_mae: 1.0120
Epoch 162/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4416 - mae: 0.5324 - val_loss: 1.5210 - val_mae: 1.0093
Epoch 163/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4289 - mae: 0.5215 - val_loss: 1.5340 - val_mae: 1.0114
Epoch 164/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4362 - mae: 0.5272 - val_loss: 1.5322 - val_mae: 1.0120
Epoch 165/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4303 - mae: 0.5238 - val_loss: 1.5173 - val_mae: 1.0091
Epoch 166/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4277 - mae: 0.5212 - val_loss: 1.5179 - val_mae: 1.0052
Epoch 167/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4297 - mae: 0.5236 - val_loss: 1.5235 - val_mae: 1.0119
Epoch 168/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4249 - mae: 0.5190 - val_loss: 1.5334 - val_mae: 1.0124
Epoch 169/200

In [26]:
#predict on train data
ypred_train=house.predict(X_train)

50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [27]:
#evaluate the train data
from sklearn.metrics import mean_squared_error
train_mse=mean_squared_error(Y_train,ypred_train)
train_rmse=np.sqrt(train_mse)
print("train RMSE:",train_rmse)

train RMSE: 0.7880300349622056

In [28]:
#predict on test data
ypred_test=house.predict(X_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [29]:
#Evaluatethe test data
test_mse=mean_squared_error(Y_test,ypred_test)
test_rmse=np.sqrt(test_mse)
print("test RMSE:",test_rmse)

test RMSE: 1.3549553610377072

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(Y_test, ypred_test)
mae = mean_absolute_error(Y_test, ypred_test)
mse = mean_squared_error(Y_test, ypred_test)

print("R2 Score:", r2)
print("MAE:", mae)
print("MSE:", mse)

R2 Score: -0.793632580400129
MAE: 1.1240459857173426
MSE: 1.8359040304048238